# Build the app image
FROM python:3.10

# Create directory for the app user
RUN mkdir -p /home/app

# Create the app user
RUN groupadd app && useradd -g app app

# Create the home directory
ENV APP_HOME=/home/app/api
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY pyproject.toml .

# Instala as dependências do projeto com o Poetry
RUN pip install poetry && \
    python -m poetry config virtualenvs.create false && \
    python -m poetry install # --without=dev

# install
COPY . .

RUN chown -R app:app $APP_HOME
USER app

CMD ["uvicorn","dundie.app:app","--host=0.0.0.0","--port=8000","--reload"]