[default]
PRIVATE_USERNAMES = ["profile",]

[default.db]
uri = ""
connect_args = {check_same_thread=false}
echo = false

[default.security]
# Set secret key in .secrets.toml
# SECRET_KEY = ""
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 5
REFRESH_TOKEN_EXPIRE_MINUTES = 500
RESET_PASS_TOKEN_EXPIRE_MINUTES = 5
PWD_RESET_URL = "https://dm.com/reset_password"
PWD_RESET_TIME_LIMIT_SECONDS = 21600

[default.email]
debug_mode = true
smtp_sender = "no-reply@dm.com"
smtp_server = "localhost"
smtp_port = 1025
smtp_user = "<replace in .secrets.toml>"
smtp_password = "<replace in .secrets.toml>"