[default]
PRIVATE_USERNAMES = ["profile",]

[default.db]
uri = ""
connect_args = {check_same_thread=false}
echo = false

[default.security]
# Set secret key in .secrets.toml
# SECRET_KEY = ""
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 5
REFRESH_TOKEN_EXPIRE_MINUTES = 500
RESET_PASS_TOKEN_EXPIRE_MINUTES = 5
PWD_RESET_URL = "http://localhost:3000/forgot-password"
PWD_RESET_TIME_LIMIT_SECONDS = 21600

[default.email]
debug_mode = true
smtp_sender = "noreply.dundie.com"
smtp_server = "localhost"
smtp_port = 25
# Set smtp_user and smtp_password in .secrets.toml
smtp_user = "dundie@dundie.com"
smtp_password = "password"