"""liked_posts

Revision ID: 494a0aa04350
Revises: 7e50aee29554
Create Date: 2024-04-26 00:27:33.634278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '494a0aa04350'
down_revision: Union[str, None] = '7e50aee29554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likedposts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name="likedposts_post_id_fkey_1", ondelete="CASCADE",),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name="likedposts_user_id_fkey_1", ondelete="CASCADE",),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index(op.f('ix_likedposts_post_id'), 'likedposts', ['post_id'], unique=False)
    op.create_index(op.f('ix_likedposts_user_id'), 'likedposts', ['user_id'], unique=False)
    op.create_index(op.f('ix_post_user_id'), 'post', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_user_id'), table_name='post')
    op.drop_index(op.f('ix_likedposts_user_id'), table_name='likedposts')
    op.drop_index(op.f('ix_likedposts_post_id'), table_name='likedposts')
    op.drop_table('likedposts')
    # ### end Alembic commands ###
