"""user model refactor

Revision ID: 71e1a49d764f
Revises: a2e05109838a
Create Date: 2024-04-04 11:19:58.239503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71e1a49d764f'
down_revision: Union[str, None] = 'a2e05109838a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balance', ['user_id'])
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.drop_column('user', 'created_at')
    op.drop_constraint(None, 'balance', type_='unique')
    # ### end Alembic commands ###
