"""Adicionado o campo 'last_password_change para armazenar a ultima vez que a senha foi alterada

Revision ID: 8c1eb267c42c
Revises: 3372da74b65e
Create Date: 2024-04-03 12:00:06.946034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c1eb267c42c'
down_revision: Union[str, None] = '3372da74b65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_password_change', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_password_change')
    # ### end Alembic commands ###
