"""is_active_and_private

Revision ID: 90f358c6ac7e
Revises: 760d6dfdefe7
Create Date: 2024-04-05 12:14:36.760589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90f358c6ac7e'
down_revision: Union[str, None] = '760d6dfdefe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('balance_user_id_fkey', 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'user', ['user_id'], ['id'])
    op.drop_constraint('transaction_from_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_user_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['from_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True, default=True))
    op.add_column('user', sa.Column('private', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'private')
    op.drop_column('user', 'is_active')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_user_id_fkey', 'transaction', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transaction_from_id_fkey', 'transaction', 'user', ['from_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key('balance_user_id_fkey', 'balance', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
