NAMES = [
    "Michael Scott",
    "Dwight Schrute",
    "Jim Halpert",
    "Pam Beesly",
    "Ryan Howard",
    "Kelly Kapoor",
    "Andy Bernard",
    "Angela Martin",
    "Stanley Hudson",
    "Phyllis Vance",
    "Oscar Martinez",
    "Kevin Malone",
    "Meredith Palmer",
    "Creed Bratton",
    "Toby Flenderson",
    "Jan Levinson",
    "David Wallace",
    "Holly Flax",
    "Darryl Philbin",
    "Erin Hannon"
]
